name: Deploy dev branch to glitch.com
on: 
  workflow_dispatch:
  push:
    branches: [ dev ]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: ${{ secrets.GIT_URL }}
        SOURCE_BRANCH: ${{ secrets.DEV_BRANCH }}
        DESTINATION_REPO: ${{ secrets.GLITCH_DEV_GIT_URL }}
        DESTINATION_BRANCH: ${{ secrets.GLITCH_DEV_BRANCH }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
